# Generated by Django 2.2.10 on 2020-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='temporary file')),
                ('life_time', models.DurationField(verbose_name='life time')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temporary file',
                'verbose_name_plural': 'Temporary files',
            },
        ),
    ]
